# Generated by Django 5.0.6 on 2024-06-17 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Specific date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='working',
            field=models.BooleanField(default=False, help_text='Is the staff member working on this day?'),
        ),
    ]
