# Generated by Django 5.0.6 on 2024-06-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshours',
            name='repeat_weekly',
            field=models.BooleanField(default=True, help_text='Automatically repeat these hours every week'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week'),
        ),
    ]
