# Generated by Django 5.0.6 on 2024-06-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_contact',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(default='+440000000000', max_length=15),
        ),
    ]
