# Generated by Django 5.0.6 on 2024-06-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0002_businesshours_repeat_weekly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshours',
            name='break_end',
            field=models.TimeField(blank=True, help_text='End time of lunch break', null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='break_start',
            field=models.TimeField(blank=True, help_text='Start time of lunch break', null=True),
        ),
    ]
