# Generated by Django 5.0.6 on 2024-06-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0003_availability_delete_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='arriving_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='leaving_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
