# Generated by Django 5.0.6 on 2024-06-13 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0003_businesshours_break_end_businesshours_break_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesshours',
            name='break_end',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='break_start',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='repeat_weekly',
        ),
        migrations.AddField(
            model_name='businesshours',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Is the business open on this day?'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='lunch_end',
            field=models.TimeField(blank=True, help_text='End of lunch break', null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='lunch_start',
            field=models.TimeField(blank=True, help_text='Start of lunch break', null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='close_time',
            field=models.TimeField(blank=True, help_text='Closing time', null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='open_time',
            field=models.TimeField(blank=True, help_text='Opening time', null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='barberapp.staff'),
        ),
    ]
