# Generated by Django 5.0.6 on 2024-06-14 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0004_remove_businesshours_break_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week')),
                ('working', models.BooleanField(default=True, help_text='Is the staff member working on this day?')),
                ('arriving_time', models.TimeField(blank=True, help_text='Arriving time', null=True)),
                ('leaving_time', models.TimeField(blank=True, help_text='Leaving time', null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='barberapp.staff')),
            ],
        ),
        migrations.DeleteModel(
            name='BusinessHours',
        ),
    ]
